### ISSUE TITLE
Don't save in JSONB type in database correctly 

### ISSUE THREAD

**Issue by ogbozoyan** [vladmihalcea/hypersistence-utils#582]
Hi, i'm using PostgreSQL, 
   application.yaml
     ```
datasource:
    url: jdbc:postgresql://localhost:5433/argroupcrm
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
```

Entity:

```
@Entity
@Table(name = "entity",schema = "public")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
public class Entity extends AbstractEntity {
@Type(type = "jsonb")
    @Column(name = "main_phones_schema")
    private List<PhoneJson> mainPhonesSchema;
}

```

PhoneJson:

```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PhoneJson implements Serializable {
    private String countryCode;
    private String phoneNumber;
}

```
     And after that all in db it saves with type uuid which causes many errors when i try to use repository.save(entity)
     <img width="562" alt="Screenshot 2023-02-19 at 13 29 43" src="https://user-images.githubusercontent.com/85520525/219942501-c0dd3bc9-94a1-459f-86bd-f5aec29d6ab6.png">

     Maybe i should design db before and after work with it ?
