### ISSUE TITLE
Spring Boot 3.1.1 doesn't find custom ObjectMapper

### ISSUE THREAD

**Issue by z0mb1ek** [vladmihalcea/hypersistence-utils#644]
I tested two version of spring boot: 3.1.0 and 3.1.1 with `io.hypersistence:hypersistence-utils-hibernate-62:3.5.1` and setting properties in application.yml like this:

```
spring:
  jpa:
    properties:
      hypersistence:
        utils:
          jackson:
            object:
              mapper: tech.livecom.libraries.utils.hibernate.CustomObjectMapperSupplier
```

In version 3.1.1 it is not working, but works in 3.1.0
